site_name: AYYAPPASWAMY EETHAKOTA

theme:
  name: material
  font: false
  custom_dir: overrides

  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.tracking

  palette:
    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - attr_list

  - toc:
      permalink: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - stylesheets/blog.css


plugins:
  - privacy

  - search:
      lang: en

  - blog:
      pagination_per_page: 6

  - tags


nav:

  - Home: index.md

  - Tech Blog:
      - Tech Blog: blog/index.md
      - Topics: blog/tags.md

  - Profile:
      - Applications & Libraries: Home/applications-and-libraries.md
      - Professional Experience: Home/professional-experience.md
      - Professional Summary: Home/Professional-Summary.md
      - Projects: Home/projects.md
      - Roles & Responsibilities: Home/roles-responsibilities.md
      - Technical Skills: Home/technical-skills.md
      

  - Documents: 

      - Important Notes: Documents/index.md

      - Bright Cluster Manager (BCM) : Documents/brightclustermanager.md

      - Disable OpenPBS Job Query: Documents/Jobs-query.md

      - GitHub Pages CI/CD: Documents/GitHub_Pages_MkDocs.md

      - CPU Hyper-Threading : Documents/hyperthreading.md

      - Configure Local Repository : Documents/Local_repo.md

      - LVM — Logical Volume Manager : Documents/Logical Volume Manager (LVM).md

      - NFS — Network File System : Documents/NFS.md

      - PIP — Python Package Manager : Documents/PIP.md

      - Proxy — Network & Internet Access : Documents/Proxy.md

      - Build RPM Packages from Source : Documents/RPM-BUILD_SOURE_CODE.md

      - Environment Modules & Module Files : Documents/Module-File.md


  - Installation: 

      - Overview: Documents/Installation/index.md

      - Applications:
          - Anaconda: Documents/Installation/Anaconda.md

          - LAMMPS:
              - Theory: Documents/Installation/lammps/theory.md
              - CPU Installation: Documents/Installation/lammps/cpu-installation.md
              - GPU Installation: Documents/Installation/lammps/gpu-installation.md
              

          - OpenFOAM: Documents/Installation/OPEN-FOAM.md
          - Python-3.14.3: Documents/Installation/Python-Offline.md
          - Quantum ESPRESSO : Documents/Installation/qe.md
          - SU2: Documents/Installation/SU2_Installation.md

      - Benchmarks:
          - HPL: Documents/Installation/hpl.md
          - HPCG: Documents/Installation/hpcg.md
          - HPCC: Documents/Installation/hpcc.md

      - Cluster & System Setup:
          - Beegfs: Documents/Installation/Cluster-System-Setup/beegfs-lab-guide.md
          - HWClock: Documents/Installation/Cluster-System-Setup/hwclock.md

          - Lustre File System:
                - Lustre: Documents/Lustre.md
                - Installation: Documents/lustre-installtion.md
                
          - LDAP (Lightweight Directory Access Protocol): Documents/Installation/Cluster-System-Setup/LDAP.md
          - OpenHPC Slurm: Documents/Installation/Cluster-System-Setup/building-an-openhpc-cluster-in-vms.md
          - OpenPBS-23.06.06: Documents/Installation/Cluster-System-Setup/OpenPBS.md
          - XCAT: Documents/Installation/Cluster-System-Setup/xcat.md
          - XCAT-Rocky8-VMware: 
                - XCAT-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/Xcat.md
                - NFS-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/Nfs.md
                - SLURM-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/Slurm.md
                - SLURM-CLIENT-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/Slurm-Client.md
                - NTP-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/ntp.md
                - Grafana-Prometheus-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/Grafana_Prometheus_Monitoring_Guide.md
                - OpenLDAP-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/openldap-setup.md
                - LDAP-Client-Configuration: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/xcat-automated-ldap-client-configuration.md
                - SNMP-Monitoring-Setup: Documents/Installation/XCAT-Setup-Rocky-8.10-on-VMware/snmp-monitoring-guide.md


      - Compilers & Toolchains:
          - GCC: Documents/Installation/gcc.md
          - Intel Toolkit: Documents/Installation/Intel-toolkit.md

      - Libraries:
          - GMP: Documents/Installation/gmp.md
          - METIS: Documents/Installation/Metis.md
          - MPC: Documents/Installation/mpc.md
          - MPFR: Documents/Installation/mpfr.md
          - OpenMPI: Documents/Installation/OpenMpi.md
          - OpenMPI-UCX: Documents/Installation/Openmpi-ucx.md


      - Sample: Documents/Installation/sample.md


  - Troubleshooting:

      - Overview: Troubleshooting/index.md

      - Hardware Troubleshooting: "Troubleshooting/Hardware Troubleshooting.md"

      - Memory Issue: "Troubleshooting/Memory issue.md"

      - Power Drain: "Troubleshooting/Power Drain.md"

      - Power Supply Unit (PSU): "Troubleshooting/Power Supply Unit.md"

      - Processor: "Troubleshooting/Processor-replaceing.md"


  - Quiz:
      - Quiz: Quiz/index.html
      

  - Contact: https://www.linkedin.com/in/ayyappaswamy-eethakota-ab3834339/